# -*- coding: utf-8 -*-
"""9.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRCw_0974QT-Wx6oELf8sfvE-cghcHMn
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('doma.csv', delimiter=';')
plt.figure(figsize=(10, 6))
plt.hist(df['price'], bins=20, color='skyblue')
plt.title('Распределение стоимости недвижимости')
plt.xlabel('Цена')
plt.ylabel('Количество')
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['yr_built'], bins=20, color='salmon')
plt.title('Распределение года постройки')
plt.xlabel('Год постройки')
plt.ylabel('Количество')
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['sqft_living'], bins=20, color='yellow')
plt.title('Распределение площади постройки')
plt.xlabel('площадь')
plt.ylabel('Количество')
plt.show()

plt.figure(figsize=(10, 6))

plt.hist(df['waterfront'], bins=2, color=['skyblue'])
plt.title('Распределение домов по наличию вида на набережную')
plt.xlabel('Вид на набережную (1 - есть, 0 - нет)')
plt.ylabel('Количество домов')
plt.xticks([0, 1], ['Нет', 'Есть'])  # Установка более читаемых меток оси x
plt.show()
count_waterfront = len(df[df['waterfront'] == 1])
print(f"Количество домов с видом на набережную: {count_waterfront}")
# Вывод: Большинство домов не имеют вида на набережную.

plt.figure(figsize=(10, 6))
plt.hist(df['floors'], bins=10, color='yellow')
plt.title('Распределение этажей домов')
plt.xlabel('Количество этажей')
plt.ylabel('Количество домов')
plt.show()

# Вывод: Большинство домов имеют 1 или 2 этажа.

plt.figure(figsize=(10, 6))

frequencies, bins, patches = plt.hist(df['condition'], bins=5, density=True)

colors = ['lightblue', 'lightgreen', 'lightcoral', 'lightyellow', 'lightgray']
for i, patch in enumerate(patches):
    patch.set_facecolor(colors[i])

plt.title('Распределение состояния домов')
plt.xlabel('Состояние (от 1 - плохое до 5 - отличное)')
plt.ylabel('Доля домов')
plt.show()

# Вывод: Большинство домов находятся в хорошем или отличном состоянии (3, 4, 5).


plt.figure(figsize=(10, 6))
plt.scatter(df['sqft_living'], df['price'], alpha=0.5)
plt.title('Влияние площади постройки на стоимость')
plt.xlabel('Площадь постройки (кв. футов)')
plt.ylabel('Стоимость (USD)')
plt.show()
# График демонстрирует положительную корреляцию между площадью жилой площади и ценой.

plt.figure(figsize=(10, 6))
plt.scatter(df['yr_built'], df['price'], alpha=0.5)
plt.title('Влияние года постройки на стоимость')
plt.xlabel('Год постройки')
plt.ylabel('Стоимость (USD)')
plt.show()
#Вывод:  На графике можно наблюдать, что стоимость домов, построенных в последние годы, в среднем выше, чем стоимость домов, построенных ранее.

plt.figure(figsize=(10, 6))
sns.boxplot(x='waterfront', y='price', data=df)
plt.title('Влияние вида на набережную на стоимость')
plt.xlabel('Вид на набережную (1 - есть, 0 - нет)')
plt.ylabel('Стоимость (USD)')
plt.show()
#Вывод:  График  boxplot  четко демонстрирует  существенную  разницу  в  стоимости  домов  с  видом  на  набережную  и  без  него.

plt.figure(figsize=(10, 6))
sns.boxplot(x='condition', y='price', data=df)
plt.title('Влияние состояния дома на стоимость')
plt.xlabel('Состояние (от 1 - плохое до 5 - отличное)')
plt.ylabel('Стоимость (USD)')
plt.show()
#Вывод: График показывает, что стоимость дома увеличивается с улучшением его состояния.  Дома с более высоким состоянием (4 и 5)  имеют более высокую  стоимость, чем  дома  с более  низким  состоянием (1, 2).

plt.figure(figsize=(10, 6))
sns.boxplot(x='floors', y='price', data=df)
plt.title('Влияние количества этажей на стоимость')
plt.xlabel('Количество этажей')
plt.ylabel('Стоимость (USD)')
plt.show()
#Вывод: На графике видно, что  стоимость домов  увеличивается  с  ростом  количества  этажей.